service: book-review-backend

frameworkVersion: "3"
useDotenv: true

provider:
  name: aws
  runtime: nodejs20.x
  stage: v1
  region: ap-southeast-1
  memorySize: 256
  apiName: ${self:service}
  versionFunctions: false
  role: arn:aws:iam::476604238413:role/LambdaAccess
functions:
  api:
    handler: src/index.handler
    timeout: 10
    reservedConcurrency: 2
    events:
      - http:
          path: /{proxy+}
          method: ANY
          cors: true

plugins: 
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-dotenv-plugin

package: 
  excludeDevDependencies: true
  include:
    - openapi.yaml
