service: book-review-backend

frameworkVersion: "3"
useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  stage: v1
  region: ap-southeast-1
  memorySize: 256
  apiName: ${self:service}
  versionFunctions: false
  role: arn:aws:iam::156041427302:role/LambdaCloudwatch
functions:
  api:
    handler: src/index.handler
    timeout: 30
    events:
      - http:
          path: /{proxy+}
          method: ANY
          cors: true

plugins: 
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-dotenv-plugin

package: 
  excludeDevDependencies: true
  include:
    - openapi.yaml
