name: Serverless Deploy

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
    - uses: actions/checkout@v3
    
    - name: Node ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install packages
      run: npm install

    - name: Copy keys
      run: echo -e '${{secrets.KEYS}}' > src/keys.json

    - name: Create .env.production file
      run: |
        echo "USERNAME=${{ vars.MONGODB_USERNAME }}" >> .env.production
        echo "PASSWORD=${{ vars.MONGODB_PASSWORD }}" >> .env.production
    
    - name: Serverless AWS authentication
      run: NODE_ENV=production yarn run sls config credentials --provider aws --key ${{ secrets.AWS_ACCESS_KEY }} --secret ${{ secrets.AWS_SECRET_KEY }}
    
    - name: Deploy Lambda functions
      run: NODE_ENV=production yarn sls deploy